//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zippers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZippersEntities : DbContext
    {
        public ZippersEntities()
            : base("name=ZippersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderManager> OrderManager { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<SferaZip> SferaZip { get; set; }
        public virtual DbSet<TypeZip> TypeZip { get; set; }
        public virtual DbSet<Zip> Zip { get; set; }
        public virtual DbSet<ZipSferaZip> ZipSferaZip { get; set; }
    }
}
