//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zippers
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderManager
    {
        public int id { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Order Order { get; set; }
    }
}
