//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zippers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipSferaZip
    {
        public int Id { get; set; }
        public Nullable<int> ZipId { get; set; }
        public Nullable<int> SferaZipId { get; set; }
    
        public virtual SferaZip SferaZip { get; set; }
        public virtual Zip Zip { get; set; }
    }
}
